server:
  port: 8081

spring:
  mvc:
    cors:
      allowed-origins: /** # 允许的源
      allowed-methods: GET, POST, PUT, DELETE # 允许的请求方法
      allowed-headers: Content-Type, Authorization # 允许的请求头
      allow-credentials: true # 是否允许携带凭证（如Cookie）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fsystem
    password: 1120
    url: jdbc:mysql://157.7.205.120/fsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



